### ISSUE TITLE
Point OHM website to Nominatim

### ISSUE THREAD

**Issue by geohacker** [OpenHistoricalMap/ohm-nominatim#7]
From @danrademacher - this likely just changing ECS Task definition:

```
 {
          "name": "OSM_nominatim_url",
          "value": "//nominatim.openstreetmap.org/"
 }
```

We should check if the front-end also needs updates.

**Comment by danrademacher** [comment]
Over in #9 I thought this might be a no-code change even but alas

@mojodna had a handy idea to just edit my local `hosts` file to see if truly the only change needed to make front-end search was a DNS repoint for `nominatim.openhistoricalmap.org`. Good test! because the answer turns out to be apparently not.

This loads fine (only on my machine or anyone who edits hosts file):
![image](https://user-images.githubusercontent.com/1423200/64899305-999d0900-d63f-11e9-8c52-992409e3ec4f.png)

AWS staging still apparently tries for openstreetmap.org:
![image](https://user-images.githubusercontent.com/1423200/64899356-cb15d480-d63f-11e9-9a78-354f79b0a492.png)

Maybe there are hardwired links in the code?

Can't search fork in GH UI, but here's results form a local search:

There are a ton of direct links to `nominatim.openstreetmap.org` in localization YMLs, but also these:
```
ohm-website/app/controllers/geocoder_controller.rb:
  168      render :action => "results"
  169    rescue StandardError => ex
  170:     @error = "Error contacting nominatim.openstreetmap.org: #{ex}"
  171      render :action => "error"
  172    end
  ...
  232      render :action => "results"
  233    rescue StandardError => ex
  234:     @error = "Error contacting nominatim.openstreetmap.org: #{ex}"
  235      render :action => "error"
  236    end

ohm-website/lib/nominatim.rb:
    7  
    8      Rails.cache.fetch "/nominatim/location/#{lat}/#{lon}/#{zoom}/#{language}" do
    9:       url = "https://nominatim.openstreetmap.org/reverse?lat=#{lat}&lon=#{lon}&zoom=#{zoom}&accept-language=#{language}"
   10  
   11        begin

ohm-website/vendor/assets/iD/iD.js:
 73317    };
 73318  
 73319:   var apibase$1 = 'https://nominatim.openstreetmap.org/',
 73320        inflight = {},
 73321        nominatimCache;
```

**Comment by danrademacher** [comment]
A couple of those are just user-facing alerts, so easy enough to change. Would be nice if they could all draw from the value in Parameter Store but not sure if that's feasible
